title: Jessica Morari - Expat and Career Coach
email: info@jessicamorari.com
description: > # Esto es solo un comentario
  Helping expats to shape their experience living abroad, designing their best life and building a fulfilling career in a foreign country
baseurl: "" # La base de tu URL, si tu sitio está en un subpath, por ejemplo: /blog
url: "https://jessicamorari.com" # La URL de tu sitio

# Construye configuraciones
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .vscode/
  - node_modules/
